version: 2
updates:
  - package-ecosystem: github-actions
    directory: /go/
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore(go)
    groups:
      go:
        patterns: ["*"]
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /node/
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore(node)
    groups:
      rust:
        patterns: ["*"]
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /rust/
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore(rust)
    groups:
      rust:
        patterns: ["*"]
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /swift/
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore(swift)
    groups:
      rust:
        patterns: ["*"]
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /python/
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: chore(python)
    groups:
      rust:
        patterns: ["*"]
    labels: [dependencies]
