name: Tree-sitter parser test (Java)
description: Test a tree-sitter parser in Java

inputs:
  java-version:
    description: Java version
    default: "25"
  distribution:
    description: Java distribution
    default: microsoft

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        cache: maven
        distribution: ${{inputs.distribution}}
        java-version: ${{inputs.java-version}}
        cache-dependency-path: pom.xml
    - name: Set up tree-sitter library
      uses: tree-sitter/setup-action/lib@v2
    - name: Build parser library
      shell: sh
      run: |-
        cmake -B build \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_INSTALL_LIBDIR=lib \
          -DCMAKE_INSTALL_BINDIR=lib \
          -DCMAKE_INSTALL_PREFIX="$RUNNER_TOOL_CACHE/tree-sitter/lib"
        cmake --build build && cmake --install build --config Debug
    - name: Run tests
      shell: sh
      run: mvn -B --no-transfer-progress test
