name: Tree-sitter parser test (Python)
description: Test a tree-sitter parser in Python

inputs:
  python-version:
    description: Python version
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        cache: pip
        python-version: ${{inputs.python-version}}
        cache-dependency-path: pyproject.toml
    - name: Build module
      shell: sh
      run: pip install -e .[core]
    - name: Run tests
      shell: sh
      run: python -munittest discover -v -s bindings/python/tests
